title: 博客标题
logo: /assets/img/logo.png
description: 这是博客的描述。
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true